version: '3.8'

services:
  web:
    build: .
    command: gunicorn stoplight.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles  # Define a volume for static files
    ports:
      - "8000:8000"
    env_file:
      - .env  # Load environment variables from .env file
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=your_database_name
      - DATABASE_USER=your_database_user
      - DATABASE_PASSWORD=your_database_password
      - DATABASE_PORT=your_database_port

volumes:
  static_volume:  # This volume is used for Django's static files

# Note: Since you're using an external MySQL database, you don't need to define a 'db' service here.
