version: '3.8'

services:
  web:
    build: .
    command: gunicorn stoplight.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env

volumes:
  static_volume:  # Just define the volume name here, no path needed
