# Generated by Django 5.0.1 on 2024-04-19 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReformArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reform',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('slcid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('criteria', models.TextField()),
                ('reform_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reforms', to='stoplight_app.reformarea')),
            ],
        ),
        migrations.CreateModel(
            name='ReformStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('R', 'Red'), ('Y', 'Yellow'), ('G', 'Green'), ('B', 'Blue'), ('K', 'Black'), ('N', 'Null')], default='N', max_length=1, null=True)),
                ('reform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stoplight_app.reform')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stoplight_app.state')),
            ],
        ),
    ]
