# Generated by Django 5.0.1 on 2024-02-06 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReformArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('slcid', models.CharField(max_length=10, unique=True)),
                ('criteria', models.CharField(max_length=100)),
                ('reform_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reforms', to='stoplight_app.reformarea')),
            ],
        ),
        migrations.CreateModel(
            name='ReformStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('reform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='stoplight_app.reform')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reform_statuses', to='stoplight_app.state')),
            ],
        ),
    ]
