# Generated by Django 5.0.7 on 2024-08-01 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stoplight_app', '0001_initial'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='reformstatus',
        #     name='notes',
        # ),
    ]
