# Generated by Django 5.0.1 on 2024-04-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stoplight_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reform',
            name='criteria',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reform',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reform',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
