# Generated by Django 5.0.7 on 2024-07-31 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stoplight_app', '0001_initial'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='historicalreformstatus',
        #     name='policy_specialist',
        # ),
        # migrations.RemoveField(
        #     model_name='reformstatus',
        #     name='policy_specialist',
        # ),
        migrations.AddField(
            model_name='reform',
            name='policy_specialist',
            field=models.TextField(blank=True, null=True),
        ),
    ]
