# Generated by Django 5.0.7 on 2024-07-31 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stoplight_app', '0002_remove_historicalreformstatus_policy_specialist_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='historicalreformstatus',
        #     name='policy_specialist',
        # ),
        # migrations.RemoveField(
        #     model_name='reformstatus',
        #     name='policy_specialist',
        # ),
    ]
