# Generated by Django 5.0.1 on 2024-05-15 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stoplight_app', '0002_alter_reform_criteria_alter_reform_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='reformstatus',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('reform_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='stoplight_app.reformstatus')),
                ('source_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stoplight_app.sourcetype')),
            ],
        ),
    ]
