# Generated by Django 5.0.7 on 2024-08-01 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stoplight_app', '0002_remove_historicalreformstatus_notes_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='reformstatus',
        #     name='citation',
        # ),
    ]
