# Generated by Django 5.0.1 on 2024-02-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stoplight_app', '0002_alter_reformstatus_reform_alter_reformstatus_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reform',
            name='criteria',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reformstatus',
            name='status',
            field=models.CharField(blank=True, choices=[('R', 'Red'), ('Y', 'Yellow'), ('G', 'Green'), ('B', 'Blue'), ('K', 'Black'), ('N', 'Null')], default='N', max_length=1, null=True),
        ),
    ]
