# Generated by Django 5.0.1 on 2024-05-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stoplight_app', '0003_sourcetype_reformstatus_additional_notes_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='reformstatus',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='source',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
