# Generated by Django 5.0.7 on 2024-08-01 19:21

from django.db import migrations
import django.utils.timezone


def set_default_last_updated(apps, schema_editor):
    Reform = apps.get_model('stoplight_app', 'Reform')
    for reform in Reform.objects.all():
        if not reform.last_updated:
            reform.last_updated = django.utils.timezone.now()
            reform.save()

class Migration(migrations.Migration):

    dependencies = [
        ('stoplight_app', '0003_remove_historicalreformstatus_citation_and_more'),
    ]

    operations = [
        migrations.RunPython(set_default_last_updated),
    ]