# Generated by Django 5.0.7 on 2024-07-31 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stoplight_app', '0004_add_notes_field'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='historicalreformstatus',
        #     name='policy_specialist',
        # ),
        # migrations.RemoveField(
        #     model_name='reformstatus',
        #     name='policy_specialist',
        # ),
        migrations.AlterField(
            model_name='reformstatus',
            name='version',
            field=models.IntegerField(default=2),
        ),
    ]
