# Generated by Django 5.0.1 on 2024-05-15 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stoplight_app', '0004_reformstatus_last_updated_source_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='title',
        ),
    ]
