# Generated by Django 5.0.7 on 2024-07-31 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stoplight_app', '0005_remove_historicalreformstatus_policy_specialist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreformstatus',
            name='version',
            field=models.IntegerField(default=2),
        ),
    ]
