# Generated by Django 5.0.7 on 2024-08-01 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stoplight_app', '0006_auto_20240801_1924'),
    ]

    operations = [
    ]
