# Generated by Django 5.0.7 on 2024-08-01 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stoplight_app', '0007_remove_historicalreformstatus_citation_and_more'),
    ]

    operations = [
    ]
