# Generated by Django 5.0.7 on 2024-07-31 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stoplight_app', '0007_add_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reformstatus',
            name='version',
            field=models.IntegerField(default=2),
        ),
    ]
