# Generated by Django 5.0.7 on 2024-08-01 20:49

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stoplight_app', '0011_historicalreformstatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='reformstatus',
        #     name='citation',
        # ),
        # migrations.RemoveField(
        #     model_name='reformstatus',
        #     name='notes',
        # ),
    ]
