# Generated by Django 5.0.7 on 2024-08-01 20:54

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stoplight_app', '0012_remove_reformstatus_citation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='reformstatus',
        #     name='citation',
        # ),
        # migrations.RemoveField(
        #     model_name='reformstatus',
        #     name='notes',
        # ),
        migrations.CreateModel(
            name='HistoricalReformStatus',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('R', 'Red'), ('Y', 'Yellow'), ('G', 'Green'), ('B', 'Blue'), ('K', 'Black'), ('N', 'Null')], default='N', max_length=1, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('win', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reform', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stoplight_app.reform')),
                ('state', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stoplight_app.state')),
            ],
            options={
                'verbose_name': 'historical reform status',
                'verbose_name_plural': 'historical reform statuss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
