# stoplight_app/migrations/0015_notes_and_citation.py
# Generated by Django 5.0.7 on 2024-08-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stoplight_app', '0013_remove_reformstatus_citation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reformstatus',
            name='citation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reformstatus',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
