# Generated by Django 5.0.7 on 2024-08-02 19:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stoplight_app', '0015_notes_and_citation'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='historicalreformstatus',
        #     name='last_updated',
        #     field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
        #     preserve_default=False,
        # ),
        migrations.AddField(
            model_name='reformstatus',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
